### ISSUE TITLE
Repo transfer

### ISSUE THREAD

**Issue by efficiosoft** [efficiosoft/btrfs-backup#14]
Hi,

I'm not sure about notifications for comments on closed pull requests... Did you get them?

Just in case you didn't:

Everything seems merged ok and ready for transfer.

Best regards
Robert

**Comment by lordsutch** [comment]
Ok. You should have gotten an email already regarding the repo transfer.

**Comment by efficiosoft** [comment]
Hmm, no, there is no mail. However, I'm receiving notifications for our conversations, so mail setup should be fine. Could you please re-check you sent the request to the correct user?

**Comment by lordsutch** [comment]
I'll abort and retry.

**Comment by efficiosoft** [comment]
Ah ok, thanks, got it. Then I'm accepting it now. You should stay as a collaborator.

**Comment by efficiosoft** [comment]
Ok, the transfer worked. Thanks for that!

I'm now going to reflect that in the README.

**Comment by lordsutch** [comment]
Looks like it went through fine. Closing...
