### ISSUE TITLE
Archlinux package

### ISSUE THREAD

**Issue by XenGi** [efficiosoft/btrfs-backup#15]
I made a [package][1] for Archlinux. You could link it in your README.
You can click the `Flag package out-of-date` button when you release a new version to notify me.

[1]: https://aur.archlinux.org/packages/python-btrfs-backup

**Comment by efficiosoft** [comment]
Hi,

thanks a lot for packaging! That's the best way to propagate new software.

I'll flag it out-of-date when a new stable version is released.

Best regards
Robert
