### ISSUE TITLE
Bad configuration option: auto_unmount

### ISSUE THREAD

**Issue by ktiedt** [efficiosoft/btrfs-backup#19]
Despite having installed sshfs and pv (since I noticed via debug that pv was missing) I still cannot manage to get around this error... Unfortunately, googling for it is nye impossible because ssh is such a prolific topic :(

Any suggestions? SSH is connecting just fine, as it creates the proper dir on the destination...

12:01:50  [INFO ]  Sending 20180414-120149 ...
12:01:50  [INFO ]    No parent snapshot available, sending in full mode.
12:01:50  [DEBUG]  Checking for pv ...
12:01:50  [DEBUG]  Executing: ['pv', '--help']
12:01:50  [DEBUG]    -> pv is available
12:01:50  [DEBUG]  Executing: ['btrfs', 'send', '/home/user/lib/snapshot/20180414-120149']
12:01:50  [DEBUG]  Executing: ['pv']
12:01:50  [DEBUG]  Executing: ['ssh', '-o', 'auto_unmount', '-o', 'reconnect', '-o', 'cache=no', 'backups', 'btrfs', 'receive', '/media/backups/user/snapshots/lib']
At subvol /home/user/lib/snapshot/20180414-120149
command-line: line 0: Bad configuration option: auto_unmount

**Comment by efficiosoft** [comment]
Hi,

Thanks for reporting this. It should be fixed now in master.

Regarding the pv command - it is completely optional and backups should work without it as well.

Can you please confirm the issue is resolved?

Best regards
Robert

**Comment by ktiedt** [comment]
Thanks! That solved that problem, however, now I am seeing a totally different one (opening a new issue since appears to be unrelated)
