### ISSUE TITLE
btrfs-backup Version?

### ISSUE THREAD

**Issue by nemysis** [efficiosoft/btrfs-backup#5]
I try to make openSUSE RPM for btrfs-backup, but can't without Version.
Please add Version file or in README.md.

**Comment by alanorth** [comment]
Just use the first 8 characters from the git commit. :)

**Comment by nemysis** [comment]
Please make Version and CHANGELOG and man, thanks :)

**Comment by efficiosoft** [comment]
Fixed, currently at v0.2
